<?php

return [
    'especies' => [
        'perro' => 'Perro',
        'gato' => 'Gato',
    ],
    'razas' => [
        'perro' => [
            'mestizo' => 'Mestizo',
            'labrador-retriever' => 'Labrador Retriever',
            'golden-retriever' => 'Golden Retriever',
            'pastor-aleman' => 'Pastor Alemán',
            'bulldog' => 'Bulldog',
            'pug' => 'Pug',
            'beagle' => 'Beagle',
            'schnauzer' => 'Schnauzer',
            'chihuahua' => 'Chihuahua',
            'pitbull' => 'Pitbull',
            'husky-siberiano' => 'Husky Siberiano',
            'shih-tzu' => 'Shih Tzu',
            'otra' => 'Otra raza',
            'no_se' => 'No sé',
        ],
        'gato' => [
            'mestizo' => 'Mestizo',
            'siames' => 'Siamés',
            'persa' => 'Persa',
            'maine-coon' => 'Maine Coon',
            'bengali' => 'Bengalí',
            'angora' => 'Angora',
            'british-shorthair' => 'British Shorthair',
            'ragdoll' => 'Ragdoll',
            'otra' => 'Otra raza',
            'no_se' => 'No sé',
        ],
    ],
    'colores' => [
        'negro' => 'Negro',
        'blanco' => 'Blanco',
        'cafe' => 'Café',
        'gris' => 'Gris',
        'beige' => 'Beige',
        'crema' => 'Crema',
        'dorado' => 'Dorado',
        'naranja' => 'Naranja',
        'amarillo' => 'Amarillo',
        'otro' => 'Otro',
    ],
    'colores_secundarios' => [
        '' => 'Sin color secundario',
        'negro' => 'Negro',
        'blanco' => 'Blanco',
        'cafe' => 'Café',
        'gris' => 'Gris',
        'beige' => 'Beige',
        'crema' => 'Crema',
        'dorado' => 'Dorado',
        'naranja' => 'Naranja',
        'amarillo' => 'Amarillo',
        'otro' => 'Otro',
    ],
    'tamanos' => [
        'pequeno' => 'Pequeño',
        'mediano' => 'Mediano',
        'grande' => 'Grande',
    ],
    'sexos' => [
        'macho' => 'Macho',
        'hembra' => 'Hembra',
        'no_se' => 'No se pudo identificar',
    ],
    'edades' => [
        'cachorro' => 'Cachorro',
        'joven' => 'Joven',
        'adulto' => 'Adulto',
        'adulto_mayor' => 'Adulto mayor',
        'no_se' => 'No se sabe',
        'otra' => 'Otra descripción',
    ],
];
