-- PetRescue: esquema para el Backend Laravel actual.
-- Ejecutar COMPLETO en Supabase > SQL Editor, con el rol postgres.
-- Admite una base vacía o el SQL original entregado por el propietario.
-- Conserva filas, claves y relaciones al renombrar. No usa DROP TABLE.
-- Si existen simultáneamente nombres antiguos y nuevos, detiene la operación
-- para evitar fusionar datos sin revisar. Toda la adaptación es transaccional.
-- No registra migraciones Laravel como ejecutadas: no sustituye su historial.

BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL search_path = public;

-- 1. Normalizar los nombres del SQL original.
DO $adaptar$
DECLARE
    cambio record;
    existe_anterior boolean;
    existe_nuevo boolean;
BEGIN
    IF to_regclass('public.imagenes_mascota') IS NOT NULL THEN
        IF to_regclass('public.imagen_mascotas') IS NOT NULL THEN
            RAISE EXCEPTION 'Existen imagenes_mascota e imagen_mascotas. Revisar ambas tablas antes de adaptar; no se ha fusionado ni borrado ninguna.';
        END IF;
        ALTER TABLE public.imagenes_mascota RENAME TO imagen_mascotas;
    END IF;

    FOR cambio IN SELECT * FROM (VALUES
        ('mascotas', 'id_mascota', 'id'),
        ('reportes', 'id_reporte', 'id'),
        ('reportes', 'id_mascota', 'mascota_id'),
        ('ubicaciones', 'id_ubicacion', 'id'),
        ('ubicaciones', 'id_reporte', 'reporte_id'),
        ('imagen_mascotas', 'id_imagen', 'id'),
        ('imagen_mascotas', 'id_mascota', 'mascota_id'),
        ('imagen_mascotas', 'url_imagen', 'ruta_imagen'),
        ('mascotas', 'fecha_registro', 'created_at'),
        ('reportes', 'fecha_creacion', 'created_at'),
        ('reportes', 'fecha_actualizacion', 'updated_at'),
        ('imagen_mascotas', 'fecha_subida', 'created_at')
    ) AS nombres(tabla, anterior, nuevo)
    LOOP
        SELECT EXISTS (SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = cambio.tabla
                AND column_name = cambio.anterior) INTO existe_anterior;
        SELECT EXISTS (SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = cambio.tabla
                AND column_name = cambio.nuevo) INTO existe_nuevo;
        IF existe_anterior AND existe_nuevo THEN
            RAISE EXCEPTION 'La tabla % contiene % y %. Revisar antes de fusionar columnas.', cambio.tabla, cambio.anterior, cambio.nuevo;
        ELSIF existe_anterior THEN
            EXECUTE format('ALTER TABLE public.%I RENAME COLUMN %I TO %I', cambio.tabla, cambio.anterior, cambio.nuevo);
        END IF;
    END LOOP;
END;
$adaptar$;

-- 2. Usuarios del SQL anterior: se conservan para sus relaciones históricas.
-- El formulario público actual guarda el contacto en reportes, sin exigir login.
CREATE TABLE IF NOT EXISTS public.usuarios (
    id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(150) NOT NULL,
    correo varchar(150) NOT NULL UNIQUE,
    telefono varchar(30),
    rol varchar(30) NOT NULL DEFAULT 'ciudadano'
        CHECK (rol IN ('propietario', 'ciudadano', 'administrador')),
    estado varchar(20) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'inactivo')),
    fecha_registro timestamptz NOT NULL DEFAULT now()
);

-- 3. Tablas que utilizan los modelos Eloquent.
CREATE TABLE IF NOT EXISTS public.mascotas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    nombre varchar(255),
    especie varchar(255),
    raza varchar(255),
    color_principal varchar(255),
    color_secundario varchar(255),
    tamano varchar(255),
    sexo varchar(255),
    edad_aproximada varchar(255),
    descripcion text,
    rasgos_distintivos text,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.reportes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario bigint REFERENCES public.usuarios(id_usuario) ON UPDATE CASCADE ON DELETE CASCADE,
    mascota_id bigint NOT NULL REFERENCES public.mascotas(id) ON UPDATE CASCADE ON DELETE CASCADE,
    tipo_reporte varchar(30) NOT NULL CHECK (tipo_reporte IN ('perdida', 'encontrada')),
    titulo varchar(255) NOT NULL,
    descripcion text,
    fecha_evento date NOT NULL,
    estado varchar(30) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo', 'cerrado', 'pendiente_revision')),
    responsable_nombre varchar(255),
    responsable_correo varchar(255),
    responsable_telefono varchar(30),
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.ubicaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporte_id bigint NOT NULL UNIQUE REFERENCES public.reportes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    direccion varchar(255),
    barrio varchar(255),
    ciudad varchar(255) NOT NULL,
    departamento varchar(255),
    latitud numeric(10,7),
    longitud numeric(10,7),
    referencia text,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.imagen_mascotas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mascota_id bigint NOT NULL REFERENCES public.mascotas(id) ON UPDATE CASCADE ON DELETE CASCADE,
    ruta_imagen varchar(500) NOT NULL,
    descripcion varchar(255),
    created_at timestamptz,
    updated_at timestamptz
);

-- 4. CREATE IF NOT EXISTS no corrige tablas existentes; estas instrucciones sí.
ALTER TABLE public.mascotas
    ADD COLUMN IF NOT EXISTS id_usuario bigint REFERENCES public.usuarios(id_usuario),
    ADD COLUMN IF NOT EXISTS created_at timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE public.mascotas
    ALTER COLUMN id_usuario DROP NOT NULL,
    ALTER COLUMN nombre TYPE varchar(255),
    ALTER COLUMN especie TYPE varchar(255),
    ALTER COLUMN raza TYPE varchar(255),
    ALTER COLUMN color_principal TYPE varchar(255),
    ALTER COLUMN color_secundario TYPE varchar(255),
    ALTER COLUMN tamano TYPE varchar(255),
    ALTER COLUMN sexo TYPE varchar(255),
    ALTER COLUMN edad_aproximada TYPE varchar(255);

ALTER TABLE public.reportes
    ADD COLUMN IF NOT EXISTS id_usuario bigint REFERENCES public.usuarios(id_usuario),
    ADD COLUMN IF NOT EXISTS responsable_nombre varchar(255),
    ADD COLUMN IF NOT EXISTS responsable_correo varchar(255),
    ADD COLUMN IF NOT EXISTS responsable_telefono varchar(30),
    ADD COLUMN IF NOT EXISTS created_at timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE public.reportes
    ALTER COLUMN id_usuario DROP NOT NULL,
    ALTER COLUMN titulo TYPE varchar(255);

ALTER TABLE public.ubicaciones
    ADD COLUMN IF NOT EXISTS created_at timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at timestamptz,
    ALTER COLUMN referencia TYPE text;
ALTER TABLE public.imagen_mascotas
    ADD COLUMN IF NOT EXISTS created_at timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- Copiar contactos reales de los usuarios históricos, sin inventar datos.
-- Se mantienen nullable para conservar reportes cuyo contacto sea desconocido.
-- Laravel valida nombre y teléfono obligatorios en las nuevas publicaciones.
UPDATE public.reportes AS r SET
    responsable_nombre = coalesce(r.responsable_nombre, u.nombre),
    responsable_correo = coalesce(r.responsable_correo, u.correo),
    responsable_telefono = coalesce(r.responsable_telefono, u.telefono)
FROM public.usuarios AS u
WHERE r.id_usuario = u.id_usuario AND
    (r.responsable_nombre IS NULL OR r.responsable_correo IS NULL OR r.responsable_telefono IS NULL);

-- Aprovechar la fecha histórica conservada; no inventar fechas de creación.
UPDATE public.mascotas SET updated_at = created_at WHERE updated_at IS NULL AND created_at IS NOT NULL;
UPDATE public.imagen_mascotas SET updated_at = created_at WHERE updated_at IS NULL AND created_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mascotas_usuario ON public.mascotas(id_usuario);
CREATE INDEX IF NOT EXISTS idx_reportes_usuario ON public.reportes(id_usuario);
CREATE INDEX IF NOT EXISTS idx_reportes_mascota ON public.reportes(mascota_id);
CREATE INDEX IF NOT EXISTS idx_reportes_tipo ON public.reportes(tipo_reporte);
CREATE INDEX IF NOT EXISTS idx_reportes_estado ON public.reportes(estado);
CREATE INDEX IF NOT EXISTS idx_reportes_created_at ON public.reportes(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_imagenes_mascota ON public.imagen_mascotas(mascota_id);
CREATE INDEX IF NOT EXISTS idx_ubicaciones_ciudad ON public.ubicaciones(ciudad);

-- 5. Tablas de infraestructura de Laravel (según sus migraciones).
-- users es el modelo de autenticación Laravel; no es public.usuarios ni auth.users.
CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    email_verified_at timestamp,
    password varchar(255) NOT NULL,
    remember_token varchar(100),
    created_at timestamp,
    updated_at timestamp
);
CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
    email varchar(255) PRIMARY KEY,
    token varchar(255) NOT NULL,
    created_at timestamp
);
CREATE TABLE IF NOT EXISTS public.sessions (
    id varchar(255) PRIMARY KEY,
    user_id bigint,
    ip_address varchar(45),
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_id_index ON public.sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_last_activity_index ON public.sessions(last_activity);
CREATE TABLE IF NOT EXISTS public.cache (
    key varchar(255) PRIMARY KEY,
    value text NOT NULL,
    expiration integer NOT NULL
);
CREATE INDEX IF NOT EXISTS cache_expiration_index ON public.cache(expiration);
CREATE TABLE IF NOT EXISTS public.cache_locks (
    key varchar(255) PRIMARY KEY,
    owner varchar(255) NOT NULL,
    expiration integer NOT NULL
);
CREATE INDEX IF NOT EXISTS cache_locks_expiration_index ON public.cache_locks(expiration);
CREATE TABLE IF NOT EXISTS public.jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue varchar(255) NOT NULL,
    payload text NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL
);
CREATE INDEX IF NOT EXISTS jobs_queue_index ON public.jobs(queue);
CREATE TABLE IF NOT EXISTS public.job_batches (
    id varchar(255) PRIMARY KEY,
    name varchar(255) NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text NOT NULL,
    options text,
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer
);
CREATE TABLE IF NOT EXISTS public.failed_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(255) NOT NULL UNIQUE,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Acceso mediante Laravel conectado como postgres (configuración actual).
-- RLS protege estas tablas de la Data API pública; no se crean políticas anon.
-- Un rol de BD distinto necesitará permisos/políticas adecuados para Laravel.
DO $rls$
DECLARE tabla text;
BEGIN
    FOREACH tabla IN ARRAY ARRAY['usuarios', 'mascotas', 'reportes', 'ubicaciones',
        'imagen_mascotas', 'users', 'password_reset_tokens', 'sessions',
        'cache', 'cache_locks', 'jobs', 'job_batches', 'failed_jobs']
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tabla);
    END LOOP;
END;
$rls$;

COMMIT;

-- Resultado de comprobación: columnas definitivas de las cuatro tablas del flujo.
SELECT table_name, column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
    AND table_name IN ('mascotas', 'reportes', 'ubicaciones', 'imagen_mascotas')
ORDER BY table_name, ordinal_position;
